# Generated by Django 4.2 on 2023-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_user', models.CharField(max_length=100)),
                ('added_by_user', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('C', 'Complete'), ('I', 'Incomplete'), ('P', 'Pending')], max_length=1)),
                ('sath_id', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
