# Generated by Django 4.2 on 2023-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sath_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('I', 'Incomplete'), ('P', 'Pending')], default='I', max_length=1),
        ),
    ]
