# Generated by Django 4.2 on 2023-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='added_by_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='added_user',
            field=models.CharField(max_length=100),
        ),
    ]
