# Generated by Django 4.2 on 2023-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_alter_group_added_by_user_alter_group_added_user'),
        ('routing', '0003_alter_group_sath_id_alter_group_status'),
    ]

    operations = [
    ]
