# Generated by Django 4.2 on 2023-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_merge_20230426_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('sathi_id', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_by', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=500)),
                ('sathi_id', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='group',
            old_name='added_by_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='added_user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sath_id',
        ),
        migrations.AddField(
            model_name='group',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='sathi_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='user_verification_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
