# Generated by Django 4.2 on 2023-05-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_chat_feedback_rename_added_by_user_group_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_given_by',
            field=models.CharField(default='', max_length=500),
        ),
    ]
