# Generated by Django 4.2 on 2023-04-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_queries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='queries',
            new_name='feedback',
        ),
    ]
