# Generated by Django 4.2 on 2023-04-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_queries_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='question',
        ),
    ]
