# Generated by Django 4.2 on 2023-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_feedback_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sathiuser',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
