# Generated by Django 4.2 on 2023-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sathiuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='sathiuser',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sathiuser',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
