# Generated by Django 4.2 on 2023-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sathiuser_city_sathiuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sathiuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
